### ISSUE TITLE
Unexpected character error when column is "text"

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#1]
Mostly, the service is working as expected, however, I was trying to diffuse on this network:

http://www.ndexbio.org/#/newNetwork/50e3dff7-133e-11e6-a039-06603eb7f303

and cytoscape threw "Cytoscape Task" "Unexpected character ("<"(code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') ...

Daniel found that deleting the "Text" edge column, which contained fields with the '<' character, allowed the service to work.  This leads me to believe that the fields are not being handled quite right somewhere in the conversion with regard to handling special characters.

**Comment by bdemchak** [comment]
Calling Diffusion still crashes. I used The RAS Machine network 

![image](https://cloud.githubusercontent.com/assets/3696094/22445150/f1761c20-e6fa-11e6-9a7e-1ab9f4b251b8.png)

[The_RAS_Machine.cx.txt](https://github.com/idekerlab/Diffusion/files/740662/The_RAS_Machine.cx.txt)

**Comment by ericsage** [comment]
The RAS machine and other networks imported via CXIO are not checked for proper UTF encoding, the service only accepts valid JSON, which must be properly UTF encoded Unicode.
