### ISSUE TITLE
Entry field for diffusion value

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#11]
It appears that the diffusion value cannot be manually entered. I don't remember whether we included this in the initial feature set or not.

If we do allow it, the input field must be robust against all erroneous entries. It is OK to accept e-notation (e.g., 1.54e-29).

**Comment by ericsage** [comment]
We've added this field for both panels.

**Comment by bdemchak** [comment]
Feedback for invalid value entry is missing (e.g., 190.555.555)

**Comment by keiono** [comment]
I'll add a validator to the text field.
