### ISSUE TITLE
Diffusion state retained across Cytoscape sessions

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#18]
Verify that the state of the Diffusion is saved in the Cytoscape session file and is restored when the session file is reloaded.

**Comment by bdemchak** [comment]
State is not maintained in saved session file. Start with galFiltered and diffuse a number of nodes. Try selecting Range Columns = diffusion_output_heat, Subnetwork Creator = size_rank, Heat Threshold = 100. Then save the session to a file, close Cytoscape, restart it and open the session file. The settings are not remembered.

**Comment by keiono** [comment]
This requires new spec for the UI saving mechanism and it is not straight forward.

**Comment by bdemchak** [comment]
Feature not required.
