### ISSUE TITLE
Heat Threshold slider is backwards

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#19]
Hot should be on the left, and Cold should be on the right. Please change the labels and make the slider work to match the labels.

**Comment by ericsage** [comment]
Slider has been inverted, labels switched

**Comment by bdemchak** [comment]
On Heat Threshold scale, Hot literal should be on the left and Cold literal should be on the right

**Comment by keiono** [comment]
![2017-04-07 18 53 28](https://cloud.githubusercontent.com/assets/73890/24824626/a1c16326-1bc3-11e7-9b86-07df182b4a71.png)
