### ISSUE TITLE
Enable diffusion when nodes are selected and right click is on an edge or background

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#2]
If I select a bunch of nodes and then right click on something besides a node, the diffusion option should be available anyway.

**Comment by keiono** [comment]
I'm not sure this is possible or not outside of the core-task implementation.

**Comment by bdemchak** [comment]
This is an important one ... Trey hit this right off, and every other naive user will, too. Consider the situation of a large hairball, and the user selects by entering a small number of nodes in the Search box. The nodes will be very hard to find in the hairball. The user will naturally right click somewhere else in the display space, and will be confused by the absence of the Diffuse menu item. Granted, he can look under Tools ... but by that time, the user is already frustrated.

**Comment by bdemchak** [comment]
Did you add the menu item to the Edge context menu, too?? I don't see it there.

**Comment by keiono** [comment]
I've added extra task factory for the edge context menu.
