### ISSUE TITLE
Clean install on v3.5 still requires CX support

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#21]
I'm installing Diffusion 1.2 from a JAR on a clean install of v3.5. The install fails because CX Support 2.1 is missing. Latest App Store release is 1.1.3. There is no CX Support in Core apps directory. I'm dead.

**Comment by keiono** [comment]
I've not deployed the CX Support 2.1 yet.

**Comment by bdemchak** [comment]
CX Support 2.1 is pushed to App Store
