### ISSUE TITLE
Node Rank tick marks too dense to read

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#22]
Using the RAS Machine network (http://www.ndexbio.org/#/newNetwork/50e3dff7-133e-11e6-a039-06603eb7f303), A diffusion gives a scale that's unreadable.

![image](https://cloud.githubusercontent.com/assets/3696094/24729694/477f78d6-1a14-11e7-8e4c-0279387a3751.png)

**Comment by keiono** [comment]
Modified to render only 4 tick marks and labels.

![2017-04-07 18 43 01](https://cloud.githubusercontent.com/assets/73890/24824540/119567b2-1bc2-11e7-9827-3c5588c3102d.png)

**Comment by bdemchak** [comment]
For RAS Machine (see below), this seems to work pretty well ... Thanks! Same for galFiltered.

I'm a little worried about the picture in the previous post. The node rank has a 6949 entry, but there isn't a tick on the far right. Is it possible for this to happen in the 1.2.2 release?? There should always be a tick on the far left and the far right ... and two in between. Please clarify.



![image](https://cloud.githubusercontent.com/assets/3696094/24967034/9c42ef58-1f5d-11e7-936e-4be077b20594.png)

**Comment by keiono** [comment]
This needs custom renderer for the JSlider.  It is possible, but not worth it comparing to the amount of code we need to do it.
