### ISSUE TITLE
Setting heat rank to 1 also selects node of rank 2

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#25]
Using the RAS machine, it's possible that selecting rank 1 gets the top *two* nodes ... even though the diffusion_output_rank column for the second node has value 2. How can this be? (BTW, the diffusion_output_heat value for both nodes are the same.)

![image](https://cloud.githubusercontent.com/assets/3696094/24967540/539e545c-1f5f-11e7-96e0-6ea86d6ca3c8.png)

**Comment by keiono** [comment]
Cannot reproduce this in v1.2.3.

**Comment by bdemchak** [comment]
This seems to be about when two nodes have the same heat. For some reason (probably incorrect), the rank slider brings the heat value into the choice of which nodes to light up. Probably not good.
