### ISSUE TITLE
Unhelpful error when attempting Diffuse without a network connection

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#7]
I disconnected the network connection and tried to Diffuse. I got an error message saying "diffuse.cytoscape.io", which doesn't explain to the user what happened and what to do next. This error (and all other error messages) must meet this standard.

**Comment by ericsage** [comment]
I completely removed non-custom errors and replies from the service and replaced them with custom messages that should be more helpful to the caller of the service. I have also used these errors to make the app errors thrown because of service issues more helpful to the end user.

**Comment by bdemchak** [comment]
Pretty good ... thanks.
