### ISSUE TITLE
Add Diffuse to Tools menu

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#8]
Diffuse must act more like a core feature and less like an app. It should have a menu item in the main Tools menu.

**Comment by bdemchak** [comment]
The current position of this menu item ranks its importance somewhere lower than Execute Command file. It deserves to be between NetworkAnalyzer and Workflow ... this is an important core feature.

**Comment by keiono** [comment]
I can change the gravity value for the menu, but even if I do it, I cannot guarantee the order because Tool menu is used by 3rd party developers and they can place the menu item anywhere under _Tools_.

**Comment by bdemchak** [comment]
Diffuse menu item now appears as a top level menu item. Is this what we intend??

**Comment by keiono** [comment]
Unnecessary top level menu has beed removed.

**Comment by bdemchak** [comment]
The Tools version of the Diffuse menu does not have the Selected Nodes with Options submenu.
