### ISSUE TITLE
Take service domain name from Cytoscape Properties

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/diffusion#9]
In case someone decides to stage the Diffusion service elsewhere (yay!), we need to allow them to do so by taking the service domain from a configurable source. If the property doesn't have a value, it's OK to default to our hard-wired domain name.

**Comment by keiono** [comment]
Now the property is called *diffusion.url* in standard Cytoscape property.

**Comment by bdemchak** [comment]
Thanks
